@startuml

title Finish Goods Inbound Workflow

|PRODUCTION USER|
start
|WAREHOUSE USER|
|AS400|
|WMS|

|PRODUCTION USER|
:input invoice details on as400 web;

|AS400|
:create case mark;
:export pre information csv;

|WMS|
:receive pre information from csv;

|PRODUCTION USER|
:stick case mark;
:transfer products to warehouse;

|WMS|
:scan case mark for receive and assign location;
:transfer to rack location;
:scan case mark and location;
:update put away;

stop
@enduml